version: '3.8'

services:
  spring-boot-app:
    image: crudnew
    container_name: my-spring-boot-app
    ports:
      - "8080:8080"
    volumes:
      - ./build/libs:/app
    working_dir: /app
    command: java -jar app.jar
